### PR TITLE
#163374300 Consume Endpoint that registers users

### PR DESCRIPTION
**Pull request by Siffersari**
### What does this PR do ?
This pull request adds consumption of the register API for the signup page
### Description of tasks to be completed?

- Consume the API to register user on the signup page

### How should you manually test this?
Clone this repository in your working directory on your computer and navigate to Questioner directory
``` 
git clone https://github.com/Siffersari/Questioner-Ultimate.git

cd Questioner-Ultimate/UI

git checkout ft-user-register-163374300 branch

```
Open **register.html** on your favorite browser

### Prerequisites

Pytest, Postman, Git,  Virtualenv

### What are the relevant PT stories?
[#163374300](https://www.pivotaltracker.com/story/show/163374300)

### Screenshots

screenshot_2019-01-22 questioner - signup

screenshot_2019-01-22 questioner - signup 1

### CODE REVIEW

**Comment by ronaldndirangu** [comment]
Add which branch should be used to test this in the description

**Comment by ronaldndirangu** [comment]
Please use the HTML required attribute for the input fields and show the error messages either above the input field the error has occurred on or through an alert

**Comment by Siffersari** [comment]
@ronaldndirangu . Thank you. I have added one.

**Comment by Siffersari** [comment]
@ronaldndirangu . Thank you for that. I am definitely going to make the error messages specific to each input

**Pull request merged**
